Some basic projectile stuff
ninjanomnom/tgstation pull request #66
Opened 2019-11-18 14:55 UTC by Couls

The projectiles position and effects will line up with the person being hit, also removes a lot of bump code and lets BYOND handle it, adds basic bounds to projectiles

2019-11-18 14:56 UTC, Couls commented on code/modules/projectiles/projectile.dm
> +	step_size = 16 // half a tile zoomer
Probably should remove this line and keep them tile based until projectiles are refactored entirely

2019-11-19 02:59 UTC, ninjanomnom requested changes

2019-11-19 02:59 UTC, ninjanomnom commented on code/__HELPERS/movement.dm
> +	if(QDELETED(thingA) || QDELETED(thingB))
let it break

2019-11-19 02:59 UTC, ninjanomnom commented on code/__HELPERS/movement.dm
> +	if(!thing)
let it break

2019-11-19 02:59 UTC, ninjanomnom commented on code/modules/projectiles/projectile.dm
> +	for(var/i in 1 to required_moves * 2) // if required moves is turfs and we move 16 pixels per pixel_move we need to double this
```suggestion
	for(var/i in 1 to required_moves * (32 / step_size)) // required moves is in turfs
```

2019-11-19 03:26 UTC, merged